<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PatientSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('patients')->insert([
            [
                'first_name' => 'Oussama',
                'last_name' => 'El Hassar',
                'phone' => '+212612345001',
                'birth_date' => '1995-04-12',
                'gender' => 'Masculin',
                'nationality' => 'Marocaine',
                'cin' => 'AB123456',
                'assurance' => 'ALLIANZ MAROC',
                'num_assurance' => '10001',
                'langue_parlee' => 'Français, Arabe',
                'photo' => null,
                'email' => 'oussama1@example.com',
                'address' => 'Marrakech, Maroc',
                'is_majeur' => true,
                'type_responsable' => null,
                'cin_responsable' => null,
                'nom_responsable' => null,
                'prenom_responsable' => null,
                'phone_responsable' => null,
                'email_responsable' => null,
                'profession_responsable' => null,
                'groupe_sanguin' => 'O+',
                'fratrie' => '2 frères, 1 sœur',
                'voie_accouchement' => 'Vaginale',
                'apgar' => '9/10',
                'allaitement' => 'Maternel',
                'developpement_psychomoteur' => 'Normal',
                'antecedents_familiaux' => 'Diabète',
                'allergies' => 'Arachides',
                'maladies_chroniques' => 'Asthme',
                'medicaments_cours' => 'Ventoline',
                'antecedents_personnels' => 'Appendicectomie',
                'hospitalisations' => 'Appendicectomie 2015',
            ],
            [
                'first_name' => 'Sara',
                'last_name' => 'El Hassar',
                'phone' => '+212612345002',
                'birth_date' => '2015-08-10',
                'gender' => 'Féminin',
                'nationality' => 'Marocaine',
                'cin' => null,
                'assurance' => 'WAFA ASSURANCE',
                'num_assurance' => '10002',
                'langue_parlee' => 'Français',
                'photo' => null,
                'email' => 'sara2@example.com',
                'address' => 'Casablanca, Maroc',
                'is_majeur' => false,
                'type_responsable' => 'Parent',
                'cin_responsable' => 'CD654321',
                'nom_responsable' => 'Ali',
                'prenom_responsable' => 'Mohamed',
                'phone_responsable' => '+212612345670',
                'email_responsable' => 'ali@example.com',
                'profession_responsable' => 'Ingénieur',
                'groupe_sanguin' => 'A+',
                'fratrie' => '1 frère',
                'voie_accouchement' => 'Césarienne',
                'apgar' => '8/10',
                'allaitement' => 'Maternel',
                'developpement_psychomoteur' => 'Normal',
                'antecedents_familiaux' => 'Hypertension',
                'allergies' => 'Lait',
                'maladies_chroniques' => 'Aucune',
                'medicaments_cours' => 'Aucun',
                'antecedents_personnels' => 'Aucune',
                'hospitalisations' => 'Aucune',
            ],
            [
                'first_name' => 'Rachid',
                'last_name' => 'Benkirane',
                'phone' => '+212612345003',
                'birth_date' => '1988-11-05',
                'gender' => 'Masculin',
                'nationality' => 'Marocaine',
                'cin' => 'CD987654',
                'assurance' => 'AXA ASSURANCE MAROC',
                'num_assurance' => '10003',
                'langue_parlee' => 'Arabe, Français',
                'photo' => null,
                'email' => 'rachid3@example.com',
                'address' => 'Rabat, Maroc',
                'is_majeur' => true,
                'type_responsable' => null,
                'cin_responsable' => null,
                'nom_responsable' => null,
                'prenom_responsable' => null,
                'phone_responsable' => null,
                'email_responsable' => null,
                'profession_responsable' => null,
                'groupe_sanguin' => 'B+',
                'fratrie' => '1 frère, 2 sœurs',
                'voie_accouchement' => 'Vaginale',
                'apgar' => '9/10',
                'allaitement' => 'Maternel',
                'developpement_psychomoteur' => 'Normal',
                'antecedents_familiaux' => 'Hypertension',
                'allergies' => 'Pollen',
                'maladies_chroniques' => 'Aucun',
                'medicaments_cours' => 'Aucun',
                'antecedents_personnels' => 'Appendicite',
                'hospitalisations' => 'Appendicectomie 2010',
            ],
        ]);
    }
}
